// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnUe2xBTt0G6RsQV7y1jdtyecDL-xNd0Q',
    appId: '1:748378346871:android:f279f747f01df955f1fd72',
    messagingSenderId: '748378346871',
    projectId: 'smart-class-ad023',
    databaseURL: 'https://smart-class-ad023-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-class-ad023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_eV-IrAEgzZiyFfaW8lKEhD4WEt5F3Jk',
    appId: '1:748378346871:ios:09a25e833c0c7acef1fd72',
    messagingSenderId: '748378346871',
    projectId: 'smart-class-ad023',
    databaseURL: 'https://smart-class-ad023-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-class-ad023.appspot.com',
    iosBundleId: 'com.domus.smarthome.domus',
  );
}
